enum EConnectStatus {
  Online = 'Online',
  Offline = 'Offline',
  Busy = 'Busy',
  Away = 'Away',
}

enum EStatus {
  UNDER_REVIEW = 'En revisión',
  PENDING = 'Pendiente de aprobación',
  APPROVED = 'Aprobado',
  REJECT = 'Rechazado',
  BANNED = 'Prohibido',
  SUSPENDED = 'Suspendido',
}

enum EApi {
  TopRatedAdvisor = 'dashboard/top-rated-advisors',
  NewRegistrations = 'dashboard/new-registrations',
  NominatedAdvisors = 'dashboard/nominated-advisors',
  AccumulatedTime = 'time-register/accumulated-time',
  AccumulatedTimeMonthly = 'time-register/accumulated-time-monthly',
  Settings = 'settings',
  Login = 'auth/sign-in',
  Logout = 'auth/sign-out',
  VerifyAccount = 'auth/verify-email',
  Register = 'auth/sign-up',
  ForgotPassword = 'auth/forgot-password',
  ResetPassword = 'auth/reset-password',
  Menu = 'web-menu',
  Advisor = 'advisor',
  Users = 'users',
  Reviews = 'review',
  UpdateAdvisorSatus = 'users/advisor/status',
  UserSummary = 'dashboard/users/summary',
  Payments = 'payments',
  Rooms = 'chat/rooms',
  CategoryMasiveUpload = 'categories/masive-upload',
  Banks = 'bank',
  BanksAccounts = 'bank-account',
  BankAccountMasiveUpload = 'bank-account/masive-upload',
  BankMasiveUpload = 'bank/masive-upload',
  Messages = 'chat/messages',
  UsersTotals = 'users/dashboard-totals-cards',
  RequestLogs = 'request-logs/group-by/asesor',
  SummaryStatus = 'request-logs/summary/status',
  SummaryMonthlyByYear = 'request-logs/summary/monthly-status',
  Categories = 'categories',
  CategoriesNoParams = 'categories/no-params',
  RateExchange = 'rate-exchange',
  Legal = 'legal',
  Planes = 'plan',
}

enum ELanguage {
  SPANISH = 'Spanish',
  ENGLISH = 'English',
}

enum EMessage {
  UnAuthorized = 'No está autorizado',
  Online = 'Online',
  Offline = 'Offline',
  Active = 'Activo',
  Inactive = 'Inactivo',
  Disconnected = 'Desconectado',
  Connected = 'Conectado',
  Welcome = 'Bienvenido',
  GoodBye = 'Hasta luego',
  Successful = 'Exitoso',
  Completed = 'Completado',
  Incompleted = 'Incompleto',
  Error = 'Error',
  GenericError = 'Ha ocurrido un error inesperado',
}

enum ERole {
  Admin = 'Admin',
  User = 'User',
  Advisor = 'Advisor',
}

enum ERoutes {
  Login = 'login',
  VerifyEmail = 'verify-email',
  Register = 'register',
  Logout = 'logout',
  Dashboard = 'dashboard',
  Landing = '',
  Home = '',
  AboutUs = 'about-us',
  AdvisorPolicy = 'advisor-policy',
  UserPolicies = 'user-policies',
  PrivacyPolicies = 'privacy-policies',
  FAQ = 'faq',
  Users = 'users',
  Advisors = 'advisors',
  Advisor = 'advisor',
  User = 'user',
  Details = 'details',
  Settings = 'settings',
  Chats = 'chats',
  RequestLogs = 'request-logs',
  Payments = 'payments',
  Categories = 'categories',
  Banks = 'banks',
  BanksAccounts = 'bank-accounts',
  Legal = 'legal',
  Planes = 'planes',
}

enum ERoutesTitles {
  Home = 'OrbeApp',
  AboutUs = 'Quienes somos',
  AdvisorPolicy = 'Políticas de asesores',
  UserPolicies = 'Políticas de usuarios',
  PrivacyPolicies = 'Políticas de privacidad',
  Login = 'Iniciar sesión',
  VerifyAccount = 'Verificar cuenta',
  Register = 'Crear cuenta',
  Dashboard = 'Dashboard',
  Users = 'Usuarios',
  User = 'Usuario',
  Advisors = 'Asesores',
  Chats = 'Chats',
  RequestLogs = 'Histórico de solicitudes',
  Payments = 'Pagos',
  Categories = 'Categorías',
  Banks = 'Bancos',
  BanksAccounts = 'Cuentas bancarias',
  PageNotFound = 'Página no encontrada',
  Legal = 'Aviso legal',
  Planes = 'Planes y paquetes',
  FAQ = 'Preguntas frecuentes',
}

enum ESocketEvent {
  Connect = 'connect',
  Disconnect = 'disconnect',
}
